(()=>{let o=e=>document.querySelector(e),a=e=>[...document.querySelectorAll(e)],c=(o("#rightMenu")||document.body.insertAdjacentHTML("beforeend",`
      <div id="rightmenu-mask" style="display:none"></div>
      <ul id="rightMenu" class="rightMenu is-hidden">
        <li><a id="menu-copytext" class="rightMenu-item is-hidden"><i class="fas fa-copy"></i><span>复制文本</span></a></li>
        <li><a id="menu-copylink" class="rightMenu-item is-hidden"><i class="fas fa-link"></i><span>复制链接</span></a></li>
        <li><a id="menu-newwindow" class="rightMenu-item is-hidden"><i class="fas fa-external-link-alt"></i><span>新窗口</span></a></li>
        <li><a id="menu-copyimg" class="rightMenu-item is-hidden"><i class="fas fa-image"></i><span>复制图片</span></a></li>
        <li><a id="menu-downloadimg" class="rightMenu-item is-hidden"><i class="fas fa-download"></i><span>下载图片</span></a></li>
        <li><a id="menu-pastetext" class="rightMenu-item is-hidden"><i class="fas fa-paste"></i><span>粘贴</span></a></li>
        <li><a id="menu-readmode" class="rightMenu-item is-hidden"><i class="fas fa-book-reader"></i><span>阅读模式</span></a></li>
        <li><a id="menu-darkmode" class="rightMenu-item"><i class="fas fa-adjust"></i><span>切换主题</span></a></li>
        <li><a id="menu-up" class="rightMenu-item"><i class="fas fa-chevron-up"></i><span>回到顶部</span></a></li>
      </ul>
    `),o("#rightMenu")),t=o("#rightmenu-mask"),r=(e,i=0,a=0)=>{e?(c.style.top=a+"px",c.style.left=i+"px",c.classList.remove("is-hidden"),t.style.display="flex"):(c.classList.add("is-hidden"),t.style.display="none")},e=(window.addEventListener("contextmenu",e=>{e.preventDefault();var i=window.getSelection().toString(),a=e.target.href,t=e.target.currentSrc,n=o(".thisisanarticle")&&!o(".thisisfof"),s=["input","textarea"].includes(e.target.tagName.toLowerCase()),{clientX:i,clientY:a}=(o("#menu-copytext").classList.toggle("is-hidden",!i),o("#menu-copylink").classList.toggle("is-hidden",!a),o("#menu-newwindow").classList.toggle("is-hidden",!a),o("#menu-copyimg").classList.toggle("is-hidden",!t),o("#menu-downloadimg").classList.toggle("is-hidden",!t),o("#menu-pastetext").classList.toggle("is-hidden",!s),o("#menu-readmode").classList.toggle("is-hidden",!n),e),t=c.offsetWidth,s=c.offsetHeight;let l=i+10,d=a;l+t>window.innerWidth&&(l-=t+20),d+s>window.innerHeight&&(d-=d+s-window.innerHeight),r(!0,d,l)}),e=>navigator.clipboard?.writeText(e));let n=!1;[["#menu-copytext",()=>e(window.getSelection().toString())],["#menu-copylink",()=>e(o("#menu-copylink")?.href||"")],["#menu-newwindow",()=>window.open(o("#menu-copylink")?.href,"_blank")],["#menu-copyimg",()=>(async e=>{try{var i=await(await fetch(e)).blob();await navigator.clipboard.write([new ClipboardItem({[i.type]:i})])}catch{await navigator.clipboard.writeText(e)}})(o("#menu-copyimg")?.dataset?.src||"")],["#menu-downloadimg",()=>{return e=o("#menu-downloadimg")?.dataset?.src||"",(i=document.createElement("a")).href=e,i.download="",void i.click();var e,i}],["#menu-pastetext",async()=>{var e,i=await navigator.clipboard?.readText?.()||"",a=document.activeElement;a&&["input","textarea"].includes(a.tagName.toLowerCase())&&(e=a.selectionStart||0,a.value=a.value.slice(0,e)+i+a.value.slice(a.selectionEnd||0),a.setSelectionRange(e+i.length,e+i.length))}],["#menu-darkmode",()=>document.querySelector('a[title="主题切换"]')?.click()],["#menu-up",()=>document.querySelector("#back-to-top")?.click()],["#menu-readmode",()=>{let i=(n=!n)?"none":"";a(".column-left, .column-right").forEach(e=>e.style.display=i),a("nav, footer, #back-to-top").forEach(e=>e.style.display=i);try{o("#waline-thread")?.parentElement.parentElement.style.display=i}catch{}var e=o(".column-main");n?(e.classList.remove("is-8-tablet","is-8-desktop","is-6-widescreen"),e.classList.add("is-10-widescreen")):(e.classList.remove("is-10-widescreen"),e.classList.add("is-8-tablet","is-8-desktop","is-6-widescreen"))}]].forEach(([e,i])=>o(e)?.addEventListener("click",()=>{i(),r()})),t.addEventListener("click",()=>r())})();